name: BuildSamples

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write
  security-events: write 

defaults:
  run:
    shell: pwsh
    
env:
  GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: 'Any CPU'
  BUILD_SOLUTION: dummy/dummy.sln

jobs:
  codeql-analyze-and-build:
    name: CodeQL Scan and Build
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']

    steps:
      - name: Print branch
        run: echo $env:GITHUB_BRANCH

      - name: Checkout source
        uses: actions/checkout@v4

      # Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: manual

      # Restore and build
      - name: Restore dependencies
        run: dotnet restore ${{ env.BUILD_SOLUTION }}

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: dotnet build ${{ env.BUILD_SOLUTION }} -p:configuration=Release -restore:True

      # Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
