name: BuildSamples

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    
permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write
  security-events: write
    
jobs:
    build-public-samples-solution:
        uses: milestonesys/internal-reusable-workflows/.github/workflows/BuildSamples-Public.yml@main
        with:
            solution: Samples\src\ComponentSamples.sln
            branch: ${{ github.head_ref || github.ref_name }}
     
    
