name: BuildSamples

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write
  security-events: write

env:
  GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
    
jobs:
    build-public-samples-solution:
        uses: milestonesys/reusable-workflows/.github/BuildSamples-Public.yml@${{env.GITHUB_BRANCH}}
        with:
            solution: Samples\src\ComponentSamples.sln
     
    
